pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:victorvisionpd/system-utilities-demo.git
          - cd system-utilities-demo.git
          - git push --mirror git@github.com:victorvision/android-system-utilities-demo.git
